openapi: 3.0.0
info:
  title: Coronatime API
  description: Here goes description
  version: 0.1.9

servers:
  - url: https://coronatime-api.vakho.redberryinternship.ge/api
    description: production server

paths:
  /all-countries:
    get:
      summary: Returns a list of countries with covid statistics.
      responses:
        "200":
          description: A JSON array of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: object
                      properties:
                        en:
                          type: string
                        ka:
                          type: string
                    countryCode:
                      type: string
                    cofirmed:
                      type: integer
                    recovered:
                      type: integer
                    critical:
                      type: integer
                    deaths:
                      type: integer
                    created_at:
                      type: string
                    update_at:
                      type: string
  /statistics-sum:
    get:
      summary: Returns sum of the covid statistics.
      responses:
        "200":
          description: A json object
          content:
            application/json:
              schema:
                type: object
                properties:
                  cofirmed:
                    type: integer
                  recovered:
                    type: integer
                  deaths:
                    type: integer
